tasks:
  - init: pip install -r requirements.txt

vscode:
  extensions:
    - almenon.arepl
    - littlefoxteam.vscode-python-test-adapter
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
